# Generated by Django 3.2 on 2022-03-04 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bandeira',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'bandeira',
                'ordering': ('descricao',),
            },
        ),
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_limite_total', models.FloatField(null=True)),
                ('valor_limite_disponivel', models.FloatField(null=True)),
                ('status_ativo', models.BooleanField(blank=True, default=True)),
                ('dia_vencimento', models.IntegerField(null=True)),
                ('dia_fechamento', models.IntegerField(null=True)),
                ('data_cadastro', models.DateTimeField(null=True)),
                ('data_atualizacao', models.DateTimeField(null=True)),
                ('bandeira', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.bandeira')),
            ],
            options={
                'db_table': 'cartao',
                'ordering': ('data_cadastro',),
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'categoria',
                'ordering': ('descricao',),
            },
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_conta', models.CharField(max_length=20, null=True)),
                ('digito_conta', models.CharField(max_length=1, null=True)),
                ('codigo_agencia', models.CharField(max_length=10, null=True)),
                ('saldo', models.FloatField(blank=True, default=0)),
                ('status_ativo', models.BooleanField(blank=True, default=True)),
                ('descricao', models.CharField(max_length=200, null=True)),
                ('data_cadastro', models.DateTimeField(null=True)),
                ('data_atualizacao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'conta',
                'ordering': ('data_cadastro',),
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('logradouro', models.CharField(blank=True, max_length=200, null=True)),
                ('numero', models.CharField(blank=True, max_length=15, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cep', models.CharField(blank=True, max_length=20, null=True)),
                ('pais', models.CharField(blank=True, max_length=50, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('data_cadastro', models.DateTimeField(blank=True)),
                ('data_atualizacao', models.DateTimeField(blank=True, null=True)),
                ('status_ativo', models.BooleanField(blank=True, default=True)),
            ],
            options={
                'db_table': 'endereco',
            },
        ),
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'forma_pagamento',
                'ordering': ('descricao',),
            },
        ),
        migrations.CreateModel(
            name='GrupoAcesso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=30, unique=True)),
                ('data_cadastro', models.DateTimeField(null=True)),
                ('data_atualizacao', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'grupo_acesso',
                'ordering': ('data_cadastro',),
            },
        ),
        migrations.CreateModel(
            name='InstituicaoFinanceira',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=100, unique=True)),
                ('codigo', models.CharField(max_length=10, null=True)),
                ('nome_completo', models.CharField(max_length=300, unique=True)),
                ('data_inicio_operacao', models.DateField(null=True)),
            ],
            options={
                'db_table': 'instituicao_financeira',
                'ordering': ('descricao',),
            },
        ),
        migrations.CreateModel(
            name='Moeda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=20, unique=True)),
                ('simbolo', models.CharField(max_length=5, null=True, unique=True)),
            ],
            options={
                'db_table': 'moeda',
                'ordering': ('descricao',),
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=300)),
                ('data_realizacao', models.DateField(blank=True, null=True)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True, null=True)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('data_previsao', models.DateField(blank=True, null=True)),
                ('parcela_atual', models.IntegerField(blank=True, null=True)),
                ('parcela_total', models.IntegerField(blank=True, null=True)),
                ('status_ativo', models.BooleanField(blank=True, default=True)),
                ('valor_pago', models.FloatField(null=True)),
                ('valor_previsao', models.FloatField()),
                ('movimentacao_sheet_id', models.UUIDField(null=True)),
                ('cartao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.cartao')),
                ('categoria', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='api.categoria')),
                ('conta_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conta_destino', to='api.conta')),
                ('conta_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conta_origem', to='api.conta')),
                ('endereco_despesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.endereco')),
                ('forma_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.formapagamento')),
                ('grupo_acesso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.grupoacesso')),
                ('moeda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.moeda')),
            ],
            options={
                'db_table': 'movimentacao',
                'ordering': ('data_atualizacao',),
            },
        ),
        migrations.CreateModel(
            name='PrioridadeMovimentacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'prioridade_movimentacao',
                'ordering': ('descricao',),
            },
        ),
        migrations.CreateModel(
            name='StatusMovimentacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'status_movimentacao',
                'ordering': ('descricao',),
            },
        ),
        migrations.CreateModel(
            name='TipoCartao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tipo_cartao',
                'ordering': ('descricao',),
            },
        ),
        migrations.CreateModel(
            name='TipoConta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tipo_conta',
                'ordering': ('descricao',),
            },
        ),
        migrations.CreateModel(
            name='TipoGrupoAcesso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'tipo_grupo_acesso',
            },
        ),
        migrations.CreateModel(
            name='TipoMovimentacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tipo_movimentacao',
                'ordering': ('descricao',),
            },
        ),
        migrations.CreateModel(
            name='UF',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'uf',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50)),
                ('sobrenome', models.CharField(blank=True, max_length=50)),
                ('data_nascimento', models.DateField(blank=True)),
                ('status_ativo', models.BooleanField(blank=True, default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, null=True)),
                ('data_atualizacao', models.DateTimeField(blank=True, null=True)),
                ('grupo_acesso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.grupoacesso')),
                ('usuario', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perfil',
                'ordering': ('data_cadastro',),
            },
        ),
        migrations.CreateModel(
            name='ParticipanteGrupoAcesso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('edicao_ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(null=True)),
                ('data_atualizacao', models.DateTimeField(null=True)),
                ('grupo_acesso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.grupoacesso')),
                ('perfil_participante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsavel_participante', to='api.perfil')),
            ],
            options={
                'db_table': 'participante_grupo_acesso',
                'ordering': ('data_cadastro',),
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(null=True)),
                ('data_atualizacao', models.DateTimeField(null=True)),
                ('valor_pagamento', models.FloatField(null=True)),
                ('conta_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conta_destino_pagamento', to='api.conta')),
                ('conta_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conta_origem_pagamento', to='api.conta')),
                ('movimentacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.movimentacao')),
                ('perfil_responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsavel_pagamento', to='api.perfil')),
            ],
            options={
                'db_table': 'pagamento',
                'ordering': ('data_cadastro',),
            },
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_cadastro', models.DateTimeField(null=True)),
                ('data_atualizacao', models.DateTimeField(null=True)),
                ('data_final', models.DateField(null=True)),
                ('valor', models.FloatField(null=True)),
                ('categoria', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='api.categoria')),
                ('perfil_responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsavel_orcamento', to='api.perfil')),
            ],
            options={
                'db_table': 'orcamento',
                'ordering': ('data_cadastro',),
            },
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='perfil_destinatario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destinatario_pagamento', to='api.perfil'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='perfil_responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsavel_movimentacao', to='api.perfil'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='prioridade',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.PROTECT, to='api.prioridademovimentacao'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='status_movimentacao',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='api.statusmovimentacao'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='tipo_movimentacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.tipomovimentacao'),
        ),
        migrations.CreateModel(
            name='MetaFinanceira',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_cadastro', models.DateTimeField(null=True)),
                ('data_atualizacao', models.DateTimeField(null=True)),
                ('data_final', models.DateField(null=True)),
                ('valor', models.FloatField(null=True)),
                ('categoria', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='api.categoria')),
                ('perfil_responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsavel_meta', to='api.perfil')),
            ],
            options={
                'db_table': 'meta_financeira',
                'ordering': ('data_cadastro',),
            },
        ),
        migrations.CreateModel(
            name='historical_perfil',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50)),
                ('sobrenome', models.CharField(blank=True, max_length=50)),
                ('data_nascimento', models.DateField(blank=True)),
                ('status_ativo', models.BooleanField(blank=True, default=True)),
                ('data_cadastro', models.DateTimeField(blank=True, editable=False, null=True)),
                ('data_atualizacao', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('grupo_acesso', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.grupoacesso')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical perfil',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='historical_pagamento',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(null=True)),
                ('data_atualizacao', models.DateTimeField(null=True)),
                ('valor_pagamento', models.FloatField(null=True)),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('conta_destino', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.conta')),
                ('conta_origem', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.conta')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('movimentacao', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.movimentacao')),
                ('perfil_responsavel', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.perfil')),
            ],
            options={
                'verbose_name': 'historical pagamento',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='historical_movimentacao',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('descricao', models.CharField(max_length=300)),
                ('data_realizacao', models.DateField(blank=True, null=True)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(blank=True, editable=False)),
                ('data_atualizacao', models.DateTimeField(blank=True, editable=False, null=True)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('data_previsao', models.DateField(blank=True, null=True)),
                ('parcela_atual', models.IntegerField(blank=True, null=True)),
                ('parcela_total', models.IntegerField(blank=True, null=True)),
                ('status_ativo', models.BooleanField(blank=True, default=True)),
                ('valor_pago', models.FloatField(null=True)),
                ('valor_previsao', models.FloatField()),
                ('movimentacao_sheet_id', models.UUIDField(null=True)),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cartao', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.cartao')),
                ('categoria', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.categoria')),
                ('conta_destino', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.conta')),
                ('conta_origem', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.conta')),
                ('endereco_despesa', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.endereco')),
                ('forma_pagamento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.formapagamento')),
                ('grupo_acesso', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.grupoacesso')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('moeda', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.moeda')),
                ('perfil_destinatario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.perfil')),
                ('perfil_responsavel', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.perfil')),
                ('prioridade', models.ForeignKey(blank=True, db_constraint=False, default=2, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.prioridademovimentacao')),
                ('status_movimentacao', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.statusmovimentacao')),
                ('tipo_movimentacao', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.tipomovimentacao')),
            ],
            options={
                'verbose_name': 'historical movimentacao',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='historical_conta',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('codigo_conta', models.CharField(max_length=20, null=True)),
                ('digito_conta', models.CharField(max_length=1, null=True)),
                ('codigo_agencia', models.CharField(max_length=10, null=True)),
                ('saldo', models.FloatField(blank=True, default=0)),
                ('status_ativo', models.BooleanField(blank=True, default=True)),
                ('descricao', models.CharField(max_length=200, null=True)),
                ('data_cadastro', models.DateTimeField(null=True)),
                ('data_atualizacao', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('grupo_acesso', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.grupoacesso')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('instituicao_financeira', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.instituicaofinanceira')),
                ('perfil_responsavel', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.perfil')),
                ('tipo_conta', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.tipoconta')),
            ],
            options={
                'verbose_name': 'historical conta',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='historical_comentario',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('texto', models.CharField(max_length=500)),
                ('data_cadastro', models.DateTimeField(null=True)),
                ('data_atualizacao', models.DateTimeField(null=True)),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('movimentacao', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.movimentacao')),
                ('perfil_responsavel', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.perfil')),
            ],
            options={
                'verbose_name': 'historical comentario',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='historical_cartao',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('valor_limite_total', models.FloatField(null=True)),
                ('valor_limite_disponivel', models.FloatField(null=True)),
                ('status_ativo', models.BooleanField(blank=True, default=True)),
                ('dia_vencimento', models.IntegerField(null=True)),
                ('dia_fechamento', models.IntegerField(null=True)),
                ('data_cadastro', models.DateTimeField(null=True)),
                ('data_atualizacao', models.DateTimeField(null=True)),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bandeira', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.bandeira')),
                ('conta', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.conta')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tipo_cartao', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.tipocartao')),
            ],
            options={
                'verbose_name': 'historical cartao',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='grupoacesso',
            name='perfil_responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsavel_grupo_acesso', to='api.perfil'),
        ),
        migrations.AddField(
            model_name='grupoacesso',
            name='tipo_grupo_acesso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.tipogrupoacesso'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='uf',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='api.uf'),
        ),
        migrations.AddField(
            model_name='conta',
            name='grupo_acesso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.grupoacesso'),
        ),
        migrations.AddField(
            model_name='conta',
            name='instituicao_financeira',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.instituicaofinanceira'),
        ),
        migrations.AddField(
            model_name='conta',
            name='perfil_responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.perfil'),
        ),
        migrations.AddField(
            model_name='conta',
            name='tipo_conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.tipoconta'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=500)),
                ('data_cadastro', models.DateTimeField(null=True)),
                ('data_atualizacao', models.DateTimeField(null=True)),
                ('movimentacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.movimentacao')),
                ('perfil_responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsavel_comentario', to='api.perfil')),
            ],
            options={
                'db_table': 'comentario',
                'ordering': ('data_cadastro',),
            },
        ),
        migrations.AddField(
            model_name='cartao',
            name='conta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.conta'),
        ),
        migrations.AddField(
            model_name='cartao',
            name='tipo_cartao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.tipocartao'),
        ),
    ]
