# Generated by Django 3.2 on 2022-03-05 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220305_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='historical_movimentacao',
            name='centro_custo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.costcenter'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='centro_custo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.costcenter'),
        ),
    ]
