# Generated by Django 3.2 on 2021-05-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210507_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historical_movimentacao',
            name='data_atualizacao',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='historical_movimentacao',
            name='data_cadastro',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
