# Generated by Django 3.2 on 2021-05-30 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210530_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentacaoIntegracaoSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movimentacao_sheet', models.IntegerField()),
                ('movimentacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.movimentacao')),
            ],
            options={
                'db_table': 'movimentacao_integracao_sheet',
            },
        ),
    ]
