# Generated by Django 3.2 on 2021-05-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_movimentacaointegracaosheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='historical_movimentacao',
            name='movimentacao_sheet_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='movimentacao_sheet_id',
            field=models.UUIDField(null=True),
        ),
        migrations.DeleteModel(
            name='MovimentacaoIntegracaoSheet',
        ),
    ]
