# Generated by Django 3.2 on 2021-05-30 20:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210530_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historical_movimentacao',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
