# Generated by Django 3.2.7 on 2022-01-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210530_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='descricao',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
