# Generated by Django 3.2 on 2022-01-26 21:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20220126_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartao',
            name='id',
        ),
        migrations.RemoveField(
            model_name='conta',
            name='id',
        ),
        migrations.RemoveField(
            model_name='historical_cartao',
            name='id',
        ),
        migrations.RemoveField(
            model_name='historical_conta',
            name='id',
        ),
        migrations.RemoveField(
            model_name='historical_pagamento',
            name='id',
        ),
        migrations.RemoveField(
            model_name='historical_perfil',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='id',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='id',
        ),
        migrations.AlterField(
            model_name='cartao',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='conta',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='historical_cartao',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='historical_conta',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='historical_pagamento',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='historical_perfil',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
