# Generated by Django 3.2 on 2022-01-26 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20220126_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conta',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='historical_conta',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='historical_pagamento',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='historical_perfil',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='pagamento',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='uuid',
            new_name='id',
        ),
    ]
