from django.urls import path
from api.views import (
    auxiliar_views, cartao_views, comentario_views, conta_views,
    endereco_views, movimentacao_views, perfil_views, meta_financeira_views,
    orcamento_views, grupo_acesso_views, participante_grupo_acesso_views
)

urlpatterns = [
    path('currencies', auxiliar_views.MoedaList.as_view()),
    path('movement-types', auxiliar_views.TipoMovimentacaoList.as_view()),
    path('methods-payments', auxiliar_views.FormaPagamentoList.as_view()),
    path('movement-status', auxiliar_views.StatusMovimentacaoList.as_view()),
    path('categories', auxiliar_views.CategoriaList.as_view()),
    path('account-types', auxiliar_views.TipoContaList.as_view()),
    path('financial-institutions', auxiliar_views.InstituicaoFinanceiraList.as_view()),
    path('brands', auxiliar_views.BandeiraList.as_view()),
    path('movment-priorities', auxiliar_views.PrioridadeMovimentacaoList.as_view()),
    path('addresses', endereco_views.EnderecoCreateListView.as_view()),
    path('addresses/<int:pk>', endereco_views.EnderecoRetrievelUpdateView.as_view()),
    path('accounts', conta_views.ContaCreateList.as_view()),
    path('accounts/<int:pk>', conta_views.ContaUpdateRetrieve.as_view()),
    path('movements', movimentacao_views.MovimentacaoCreateList.as_view()),
    path('movements/<str:pk>', movimentacao_views.MovimentacaoUpdateRetrieve.as_view()),
    path('profiles', perfil_views.PerfilCreateListView.as_view()),
    path('profiles/<int:pk>', perfil_views.PerfilRetrieveUpdateView.as_view()),
    path('comments', comentario_views.ComentarioCreateList.as_view()),
    path('comments/<int:pk>', comentario_views.ComentarioUpdateRetrieve.as_view()),
    path('cards', cartao_views.CartaoCreateList.as_view()),
    path('cards/<int:pk>', cartao_views.CartaoUpdateRetrieve.as_view()),
    path('goals', meta_financeira_views.MetaFinanceiraCreateListView.as_view()),
    path('goals/<int:pk>', meta_financeira_views.MetaFinanceiraUpdateView.as_view()),
    path('budgets', orcamento_views.OrcamentoCreateListView.as_view()),
    path('orcamentos/<int:pk>', orcamento_views.OrcamentoUpdateView.as_view()),
    path('sheet_sync', movimentacao_views.SyncMovimentacaoSheet.as_view()),
    path('sheet-movements', movimentacao_views.MovimentacaoSheetList.as_view()),
    path('access-group-types', auxiliar_views.TipoGrupoAcessoList.as_view()),
    path('access-group', grupo_acesso_views.GrupoAcessoCreateList.as_view()),
    path('access-group/<int:pk>', grupo_acesso_views.GrupoAcessoUpdate.as_view()),
    path('access-group-participant', participante_grupo_acesso_views.ParticipanteGrupoAcessoCreateList.as_view()),
    path('access-group-participant/<int:pk>', participante_grupo_acesso_views.ParticipanteGrupoAcessoUpdate.as_view()),
]
